#!/usr/bin/env bash
# vim: set filetype=sh :

set -e

hash jupyter 2>/dev/null || {
    echo >&2 "Can't find 'jupyter' program. Exiting"
    exit 1
}

service="lab"
if [[ "$1" == "notebook" ]]; then
    service="notebook"
    shift
elif [[ "$1" == "lab" ]]; then
    shift
fi
echo "Launching a Jupyter $service session"

set -u

echo "None $@"
echo "1 ${@:1}"
echo "2 ${@:2}"

job_name=session_jupyter_${service}
echo "qsub \
    -V \
    -l h_rt=24:00:00 \
    -l eth_speed=10 \
    -j y \
    -b y \
    -N $job_name \
    jupyter "$service" "${@:1}" 2>&1
"
exit
qsub_msg=$(qsub \
    -V \
    -l h_rt=24:00:00 \
    -l eth_speed=10 \
    -j y \
    -b y \
    -N $job_name \
    jupyter "$service" "$@" 2>&1)
qsub_jid=$(echo $qsub_msg | awk '{ print $3 }')
echo "$qsub_msg"


# Check in on the job, finding the server to SSH into
log_file=${job_name}.o${qsub_jid}
echo "Finding the server the notebook is running on..."
echo "Searching for log file: ${log_file}"
while true; do
    if [ -f $log_file ]; then 
        jip=$(grep "The Jupyter Notebook is running at" $log_file | \
              awk -F ':' '{ print $NF }' | tr -d '\/:')
        if [ ! -z "$jip" ]; then
            jupyter_host=$(qstat -u $USER | \
                           grep $qsub_jid | \
                           awk '{ print $8 }' | \
                           awk -F '@' '{ print $2 }')
            echo "Running on ${jupyter_host}:${jip}"
            echo "Try..."
            echo "ssh -L localhost:${jip}:${jupyter_host}:${jip} ${USER}@${HOSTNAME}"
            break
        fi
    fi
    sleep 5
    echo -n "."
done
